version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/acg-ocr/
  - source: /acg-ocr.service
    destination: /etc/systemd/system/acg-ocr.service
hooks:
  AfterInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root
    - location: scripts/start_server.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/application_start.sh
      timeout: 10
      runas: ec2-user
  ApplicationStop:
    - location: scripts/application_stop.sh
      timeout: 10
      runas: root