version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/acg-ocr/
    overwrite: true
  - source: /acg-ocr.service
    destination: /etc/systemd/system/
    overwrite: true
file_exists_behavior: OVERWRITE
hooks:
  AfterInstall:
    - location: scripts/post_install.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: scripts/application_start.sh
      timeout: 10
      runas: ec2-user
  ApplicationStop:
    - location: scripts/application_stop.sh
      timeout: 10
      runas: ec2-user